### ISSUE TITLE
update model repo

### ISSUE THREAD

**Issue by SaadShamim** [lucataco/cog-qwen-vl-chat#1]
hey @lucataco Qwen removed their model from hugging face so this is breaking on replicate. On their official discord(https://discord.com/channels/1138691447068049478/1140483768252117003), there is a clone at: https://huggingface.co/adieyal/Qwen-VL-Chat ("adieyal/Qwen-VL-Chat").

Can you update the model? I tried creating a pr but I don't have permission, and my laptop is too weak to build the image and create a fork on replicate.

**Comment by lucataco** [comment]
It seems that they are working on it, so I'll leave it as is:
[https://github.com/QwenLM/Qwen-7B/issues/295](https://github.com/QwenLM/Qwen-7B/issues/295)
_"The issue is being resolved quickly and is expected to be restored soon"_

**Comment by m-ali-awan** [comment]
Hi @lucataco 
hope you are fine.
Thanks for your wonderful demo-space on Replicate.
Can, I ddeploy that space, so it scales-up and down, based on usage, and i only pay for the up time. I see, on site, they have tutorial as well, how can I deploy it as serverless on Replicate.

Thanks
